spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    session:
      timeout: 900
      cookie:
        http-only: false
        secure: false